# Generated by Django 2.1.5 on 2019-02-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('SPRING I', 'SPRING I'), ('SPRING II', 'SPRING II'), ('SUMMER I', 'SUMMER I'), ('SUMMER II', 'SUMMER II'), ('FALL I', 'FALL I'), ('FALL II', 'FALL II')], max_length=255)),
                ('github', models.URLField(blank=True, null=True)),
                ('project_management', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_hidden', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
