# Generated by Django 2.1.5 on 2019-02-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_file_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/'),
        ),
    ]
